apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: controlplane-addons-accesspolicy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      namespaces:
      - gloo-mesh-addons
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster1
        name: istio-ingressgateway-service-account
        namespace: istio-system
      - clusterName: cluster2
        name: istio-ingressgateway-service-account
        namespace: istio-system
      - clusterName: cluster3
        name: istio-ingressgateway-service-account
        namespace: istio-system
  - kubeIdentityMatcher:
      namespaces:
      - gloo-mesh-addons