apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.12.6
    helm:
      values: |
        # Name allows overriding the release name. Generally this should not be set
        name: ""
        # revision declares which revision this gateway is a part of
        revision: "1-12"
        
        replicaCount: 1
        
        service:
          # Type of service. Set to "None" to disable the service entirely
          type: LoadBalancer
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 80
          - name: https
            port: 443
            protocol: TCP
            targetPort: 443
          annotations: {}
          loadBalancerIP: ""
          loadBalancerSourceRanges: []
          externalTrafficPolicy: ""
        
        # Pod environment variables
        env: {}
        
        # Labels to apply to all resources
        labels:
          istio.io/rev: 1-12
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - #group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - #group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks