apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-mgmt-mesh-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: HEAD
    path: environments/mgmt/mesh-config/3-cluster-demo/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false