apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  labels:
    workspace.solo.io/exported: "true"
  name: bookinfo
  namespace: bookinfo-frontends
spec:
  applyToRoutes:
  - route:
      labels:
        ratelimited: "true"
  config:
    ratelimitClientConfig:
      cluster: cluster1
      name: bookinfo
      namespace: bookinfo-frontends
    ratelimitServerConfig:
      cluster: cluster1
      name: bookinfo
      namespace: gloo-mesh-addons
    serverSettings:
      cluster: cluster1
      name: bookinfo-rate-limit-server
      namespace: bookinfo-frontends
