apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-enterprise-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  project: default
  source:
    chart: gloo-mesh-enterprise
    helm:
      values: |
        licenseKey: eyJleHAiOjE2NDQwODE1MjYsImlhdCI6MTY0MzQ3NjcyNiwiayI6InFXL2pOQSIsImx0IjoidHJpYWwiLCJwcm9kdWN0IjoiZ2xvbyJ9.wQIi88rkPCMPAHe98VgdQ_qRdYP3Y_Seyw6i0JywEjY
    repoURL: https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-enterprise
    targetRevision: 1.2.9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 