apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: delegated-table-1
  namespace: collaboration-tools
  labels:
    expose: "true"
    table: ghost
spec:
  weight: 100
  http:
    - name: ghost-main
      labels:
        waf: "true"
        ratelimited: "true"
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
        - ref:
            name: blog
            namespace: collaboration-tools
          port:
            number: 443