apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  labels:
    workspace.solo.io/exported: "true"
  name: ghost-rlp
  namespace: collaboration-tools
spec:
  applyToRoutes:
  - route:
      labels:
        ratelimited: "true"
  config:
    ratelimitClientConfig:
      cluster: mgmt
      name: ghost-rlcc
      namespace: collaboration-tools
    ratelimitServerConfig:
      cluster: mgmt
      name: ghost-rlsc
      namespace: gloo-mesh-addons
    serverSettings:
      cluster: mgmt
      name: ghost-rlss
      namespace: collaboration-tools
