apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: gm-ui-rt-443
  namespace: gloo-mesh
spec:
  hosts:
  - '*'
  http:
  - name: redirect
    matchers:
    # Prefix matching for the old path
    - uri:
        prefix: /gmui
    # Redirection to the desired path
    redirect:
      pathRedirect: /
  - name: gloo-mesh-ui
    matchers:
    - uri:
        exact: /
    - uri:
        exact: /welcome
    - uri:
        prefix: /static
    - uri:
        prefix: /login
    - uri:
        prefix: /rpc
    - uri:
        prefix: /workspace
    - uri:
        prefix: /oidc-callback
    forwardTo:
      destinations:
      - ref:
          name: gloo-mesh-ui
          namespace: gloo-mesh
        port:
          number: 8090
    labels:
      waf: "true"
  virtualGateways:
  - cluster: mgmt
    name: mgmt-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []