---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: bookinfo-gateway-productpage-accesspolicy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      labels:
        service: productpage
      namespaces:
      - default
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster1
        name: istio-ingressgateway-service-account
        namespace: istio-system
      - clusterName: cluster2
        name: istio-ingressgateway-service-account
        namespace: istio-system
      - clusterName: cluster3
        name: istio-ingressgateway-service-account
        namespace: istio-system
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: bookinfo-productpage-details-reviews-accesspolicy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      labels:
        service: details
      namespaces:
      - default
  - kubeServiceMatcher:
      labels:
        service: reviews
      namespaces:
      - default
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster1
        name: bookinfo-productpage
        namespace: default
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster2
        name: bookinfo-productpage
        namespace: default
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster3
        name: bookinfo-productpage
        namespace: default
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: bookinfo-reviews-ratings-accesspolicy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      labels:
        service: ratings
      namespaces:
      - default
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster1
        name: bookinfo-reviews
        namespace: default
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster2
        name: bookinfo-reviews
        namespace: default
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster3
        name: bookinfo-reviews
        namespace: default
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: istio-ingressgateway-accesspolicy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      labels:
        service: productpage
      namespaces:
      - default
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: cluster1
        name: istio-ingressgateway-service-account
        namespace: istio-system
      - clusterName: cluster2
        name: istio-ingressgateway-service-account
        namespace: istio-system
      - clusterName: cluster3
        name: istio-ingressgateway-service-account
        namespace: istio-system